env:
  DOCKER_COMPOSE_VERSION: 1.13.0

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  #  Generate jwt keys
  - pwd && ls -ahl
  - cd servercode/resources && ../scripts/keygen.sh && ls -ahl && cd -

script:
  - docker-compose -f compose-base.yml -f compose-test.yml -p backend-nodejs up -d
  - docker logs -f backendnodejs_backend-nodejs_1
  - docker wait backendnodejs_backend-nodejs_1
  - docker-compose -f compose-base.yml -f compose-test.yml stop

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_API_KEY
    skip_cleanup: true
    on:
      tags: true
      branch: release