version: '3'
services:
  backend-nodejs:
    build: ./servercode
    links:
     - "mongo"
    ports:
     - "3000:3000"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
