version: '3.1'
services:
  frontend:
    build: ./webclient
    links:
      - "backend-nodejs"

  backend-nodejs:
    build: ./servercode
    links:
     - "mongo"

  mongo:
    image: "jixer/rpi-mongo"
#    command: "--smallfiles --logpath=/dev/null"
