version: '3.1'
services:
  frontend:
    build: ./webclient
    links:
      - "backend-nodejs"
    ports:
      - "8080:8080"

  backend-nodejs:
    build: ./servercode
    links:
     - "mongo"
    ports:
     - "3000:3000"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
