version: '3'
services:
  backend-nodejs:
    environment:
      - ENV=DEV
    volumes:
      - ./servercode:/usr/src/app
    command: >
        sh -c '
        echo "Running backend";
        if test -d node_modules;
        then
          echo "node_modules_exists";
          rm -rf node_modules;
        fi
        && cp -a /tmp/node_modules /usr/src/app
        && nodemon src/index.js;
        '

  frontend:
    volumes:
      - ./webclient:/usr/src/app
    command: >
        sh -c '
        echo "Running frontend";
        if test -d node_modules;
        then
          echo "node_modules_exists";
          rm -rf node_modules;
        fi 
        && cp -a /tmp/node_modules /usr/src/app 
        && npm run dev;
        '
